CREATE TABLE [USR].[User] (
    [UserId]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [UserStatusId]       BIGINT        NOT NULL,
    [UserLogin]          VARCHAR (200) NULL,
    [UserPassword]       VARCHAR (200) NULL,
    [LastAccessDateTime] DATETIME      NULL,
    [OrganizationId]     BIGINT        NOT NULL,
    [UserTypeId]         BIGINT        NULL,
    [EmailAddress]       VARCHAR (80)  NULL,
    [ActivationDate]     DATETIME      NULL,
    [ContractDate]       DATETIME      NULL,
    [UserSpecialtyId]    BIGINT        NULL,
    [EntityId]           BIGINT        NOT NULL,
    [FacilityId]         BIGINT        NOT NULL,
    [Answer]             VARCHAR (256) NULL,
    [SecurityQuestionId] BIGINT        NULL,
    [CreatedDateTime]    DATETIME      NOT NULL,
    [ModifiedDateTime]   DATETIME      NOT NULL,
    [CreatedByUser]      VARCHAR (80)  NOT NULL,
    [ModifiedByUser]     VARCHAR (80)  NULL,
    [CreatedByProgram]   VARCHAR (80)  NOT NULL,
    [ModifiedByProgram]  VARCHAR (80)  NULL,
    [RecordStatus]       INT           NOT NULL,
    CONSTRAINT [PK_User] PRIMARY KEY NONCLUSTERED ([UserId] ASC),
    CONSTRAINT [R_203] FOREIGN KEY ([UserStatusId]) REFERENCES [USR].[UserStatus] ([UserStatusId]),
    CONSTRAINT [R_565] FOREIGN KEY ([OrganizationId]) REFERENCES [FAC].[Organization] ([OrganizationId]),
    CONSTRAINT [R_579] FOREIGN KEY ([UserTypeId]) REFERENCES [USR].[UserType] ([UserTypeId]),
    CONSTRAINT [R_592] FOREIGN KEY ([UserSpecialtyId]) REFERENCES [USR].[UserSpecialty] ([UserSpecialtyId]),
    CONSTRAINT [R_637] FOREIGN KEY ([EntityId]) REFERENCES [FAC].[Entity] ([EntityId])
);

