CREATE TABLE [CLI].[DocumentManagement] (
    [DocumentManagementId]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [DocumentPath]          VARCHAR (500) NULL,
    [PatientId]             BIGINT        NULL,
    [EstimateRunDateTime]   DATETIME      NULL,
    [DocumentCategoryId]    BIGINT        NOT NULL,
    [DocumentSubCategoryId] BIGINT        NOT NULL,
    [TemplateName]          VARCHAR (250) NULL,
    [TemplateContent]       VARCHAR (1)   NULL,
    [Notes]                 VARCHAR (250) NULL,
    [OnlineUploadTime]      DATETIME      NULL,
    [OfflineUploadTime]     DATETIME      NULL,
    [OnlineOrOfflineStatus] INT           NULL,
    [OrderId]               INT           NULL,
    [RadiologistDetails]    VARCHAR (250) NULL,
    [InterpretationDetails] VARCHAR (250) NULL,
    [SignedStatusId]        INT           NULL,
    [ConsentStatus]         VARCHAR (10)  NULL,
    [FacilityId]            BIGINT        NULL,
    [CreatedDateTime]       DATETIME      NOT NULL,
    [ModifiedDateTime]      DATETIME      NOT NULL,
    [CreatedByUser]         VARCHAR (80)  NOT NULL,
    [ModifiedByUser]        VARCHAR (80)  NULL,
    [CreatedByProgram]      VARCHAR (80)  NOT NULL,
    [ModifiedByProgram]     VARCHAR (80)  NULL,
    [RecordStatus]          INT           NOT NULL,
    CONSTRAINT [PK_DocumentManagement] PRIMARY KEY CLUSTERED ([DocumentManagementId] ASC),
    CONSTRAINT [R_389] FOREIGN KEY ([DocumentSubCategoryId]) REFERENCES [CLI].[DocumentSubCategory] ([DocumentSubCategoryId]),
    CONSTRAINT [R_390] FOREIGN KEY ([DocumentCategoryId]) REFERENCES [CLI].[DocumentCategory] ([DocumentCategoryId]),
    CONSTRAINT [R_487] FOREIGN KEY ([PatientId]) REFERENCES [PER].[Patient] ([PatientId]),
    CONSTRAINT [R_488] FOREIGN KEY ([FacilityId]) REFERENCES [FAC].[Facility] ([FacilityId])
);

