CREATE TABLE [CLI].[PerioChart] (
    [PerioChartId]           BIGINT       IDENTITY (1, 1) NOT NULL,
    [PerioChartName]         VARCHAR (50) NULL,
    [Score1]                 SMALLINT     CONSTRAINT [DF_PerioChart_Score1] DEFAULT ((0)) NULL,
    [Score2]                 SMALLINT     CONSTRAINT [DF_PerioChart_Score2] DEFAULT ((0)) NULL,
    [Score3]                 SMALLINT     CONSTRAINT [DF_PerioChart_Score3] DEFAULT ((0)) NULL,
    [Score4]                 SMALLINT     CONSTRAINT [DF_PerioChart_Score4] DEFAULT ((0)) NULL,
    [Score5]                 SMALLINT     CONSTRAINT [DF_PerioChart_Score5] DEFAULT ((0)) NULL,
    [Score6]                 SMALLINT     CONSTRAINT [DF_PerioChart_Score6] DEFAULT ((0)) NULL,
    [IsCompleted]            SMALLINT     CONSTRAINT [PerioChart_IsCompleted] DEFAULT ((1)) NULL,
    [LAAId]                  BIGINT       NULL,
    [PerioChangeToothId]     BIGINT       NULL,
    [CreatedDateTime]        DATETIME     NOT NULL,
    [ModifiedDateTime]       DATETIME     NOT NULL,
    [CreatedByUser]          VARCHAR (80) NOT NULL,
    [ModifiedByUser]         VARCHAR (80) NULL,
    [CreatedByProgram]       VARCHAR (80) NOT NULL,
    [ModifiedByProgram]      VARCHAR (80) NULL,
    [RecordStatus]           INT          NOT NULL,
    [PerioExamId]            BIGINT       NULL,
    [PatientToothId]         BIGINT       NULL,
    [ToothTypeId]            BIGINT       NULL,
    [ConditionBySextantId]   BIGINT       NULL,
    [ConditionsOnAllTeethId] BIGINT       NULL,
    [BrushTypeId]            BIGINT       NULL,
    [TobaccoTypeId]          BIGINT       NULL,
    [CaseTypeId]             BIGINT       NULL,
    CONSTRAINT [PK_PERIOCHART] PRIMARY KEY CLUSTERED ([PerioChartId] ASC),
    CONSTRAINT [R_234] FOREIGN KEY ([PerioChangeToothId]) REFERENCES [CLI].[PerioChangeTooth] ([PerioChangeToothId]),
    CONSTRAINT [R_788] FOREIGN KEY ([PerioExamId]) REFERENCES [CLI].[PerioExam] ([PerioExamId]),
    CONSTRAINT [R_789] FOREIGN KEY ([PatientToothId]) REFERENCES [CLI].[PatientTooth] ([PatientToothId]),
    CONSTRAINT [R_790] FOREIGN KEY ([ToothTypeId]) REFERENCES [CLI].[ToothType] ([ToothTypeId]),
    CONSTRAINT [R_898] FOREIGN KEY ([ConditionBySextantId]) REFERENCES [CLI].[ConditionBySextant] ([ConditionBySextantId]),
    CONSTRAINT [R_899] FOREIGN KEY ([ConditionsOnAllTeethId]) REFERENCES [CLI].[ConditionsOnAllTeeth] ([ConditionsOnAllTeethId]),
    CONSTRAINT [R_900] FOREIGN KEY ([BrushTypeId]) REFERENCES [CLI].[BrushType] ([BrushTypeId]),
    CONSTRAINT [R_901] FOREIGN KEY ([TobaccoTypeId]) REFERENCES [CLI].[TobaccoType] ([TobaccoTypeId]),
    CONSTRAINT [R_902] FOREIGN KEY ([CaseTypeId]) REFERENCES [CLI].[CaseType] ([CaseTypeId])
);

