CREATE TABLE [CLI].[VitalState] (
    [VitalStateId]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [PatientId]             BIGINT         NOT NULL,
    [VitalDate]             DATETIME       NULL,
    [Weight]                DECIMAL (5, 2) NULL,
    [Height]                DECIMAL (5, 2) NULL,
    [Temperature]           DECIMAL (5, 2) NULL,
    [Pulse]                 INT            NULL,
    [VitalStateDescription] VARCHAR (255)  NULL,
    [Respiration]           INT            NULL,
    [BMI]                   DECIMAL (5, 2) NULL,
    [HeartRate]             INT            NULL,
    [SeverityOfPain]        INT            NULL,
    [CreatedDateTime]       DATETIME       NOT NULL,
    [ModifiedDateTime]      DATETIME       NOT NULL,
    [CreatedByUser]         VARCHAR (80)   NOT NULL,
    [ModifiedByUser]        VARCHAR (80)   NULL,
    [CreatedByProgram]      VARCHAR (80)   NOT NULL,
    [ModifiedByProgram]     VARCHAR (80)   NULL,
    [RecordStatus]          INT            NOT NULL,
    [EmployeeId]            BIGINT         NULL,
    [WeightMeasurementId]   BIGINT         NULL,
    [HeightMeasurementId]   BIGINT         NULL,
    [PulseRhythmTypeId]     BIGINT         NULL,
    [BMIStatusId]           BIGINT         NULL,
    CONSTRAINT [PK_Vital] PRIMARY KEY CLUSTERED ([VitalStateId] ASC),
    CONSTRAINT [R_179] FOREIGN KEY ([PatientId]) REFERENCES [PER].[Patient] ([PatientId]),
    CONSTRAINT [R_776] FOREIGN KEY ([EmployeeId]) REFERENCES [FAC].[Employee] ([EmployeeId]),
    CONSTRAINT [R_886] FOREIGN KEY ([WeightMeasurementId]) REFERENCES [CLI].[WeightMeasurement] ([WeightMeasurementId]),
    CONSTRAINT [R_887] FOREIGN KEY ([HeightMeasurementId]) REFERENCES [CLI].[HeightMeasurement] ([HeightMeasurementId]),
    CONSTRAINT [R_888] FOREIGN KEY ([PulseRhythmTypeId]) REFERENCES [CLI].[PulseRhythmType] ([PulseRhythmTypeId]),
    CONSTRAINT [R_889] FOREIGN KEY ([BMIStatusId]) REFERENCES [CLI].[BMIStatus] ([BMIStatusId])
);

