CREATE TABLE [TRE].[PatientProcedureLog] (
    [PatientProcedureLogId]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [PatientTreatmentPlanId] BIGINT        NULL,
    [VisitId]                BIGINT        NULL,
    [Surface]                VARCHAR (10)  NULL,
    [Tooth]                  INT           NULL,
    [ToothRange]             VARCHAR (100) NULL,
    [MesialShift]            INT           NULL,
    [MesialRotate]           INT           NULL,
    [OcclusalShift]          INT           NULL,
    [OcclusalRotate]         INT           NULL,
    [FacialShift]            INT           NULL,
    [FacialRotate]           INT           NULL,
    [ProcedureOption]        INT           NULL,
    [FacilityId]             BIGINT        NOT NULL,
    [DateOfService]          DATETIME      NULL,
    [PatientProcedureId]     BIGINT        NULL,
    [CreatedDateTime]        DATETIME      NOT NULL,
    [ModifiedDateTime]       DATETIME      NOT NULL,
    [CreatedByUser]          VARCHAR (80)  NOT NULL,
    [ModifiedByUser]         VARCHAR (80)  NULL,
    [CreatedByProgram]       VARCHAR (80)  NOT NULL,
    [ModifiedByProgram]      VARCHAR (80)  NULL,
    [RecordStatus]           INT           NOT NULL,
    [PatientId]              BIGINT        NULL,
    [PatientToothId]         BIGINT        NULL,
    [AccountId]              BIGINT        NULL,
    [EntityId]               BIGINT        NULL,
    [OrganizationId]         BIGINT        NULL,
    CONSTRAINT [PK_TxPlanProcedure] PRIMARY KEY NONCLUSTERED ([PatientProcedureLogId] ASC),
    CONSTRAINT [R_417] FOREIGN KEY ([PatientProcedureId]) REFERENCES [TRE].[PatientProcedure] ([PatientProcedureId]),
    CONSTRAINT [R_829] FOREIGN KEY ([PatientToothId]) REFERENCES [CLI].[PatientTooth] ([PatientToothId])
);

