CREATE TABLE [TRE].[PatientProcedure] (
    [PatientProcedureId]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [CategoryFilterId]              BIGINT         NULL,
    [VisitId]                       BIGINT         NULL,
    [Tooth]                         INT            NULL,
    [Surface]                       VARCHAR (10)   NULL,
    [Fee]                           DECIMAL (8, 2) NULL,
    [CouponDiscount]                DECIMAL (8, 2) NULL,
    [EstimatedInsuranceDiscount]    DECIMAL (8, 2) NULL,
    [EstimatedInsuranceBenefit]     DECIMAL (8, 2) NULL,
    [PatientFinancialResposibility] DECIMAL (8, 2) NULL,
    [ToothQuadrantCode]             VARCHAR (20)   NULL,
    [SurfaceCode]                   VARCHAR (20)   NULL,
    [IsFeeManual]                   SMALLINT       NULL,
    [CreatedDateTime]               DATETIME       NOT NULL,
    [ModifiedDateTime]              DATETIME       NOT NULL,
    [CreatedByUser]                 VARCHAR (80)   NOT NULL,
    [ModifiedByUser]                VARCHAR (80)   NULL,
    [CreatedByProgram]              VARCHAR (80)   NOT NULL,
    [ModifiedByProgram]             VARCHAR (80)   NULL,
    [RecordStatus]                  INT            NOT NULL,
    [MasterProcedureId]             BIGINT         NULL,
    [IsProcedureApprovalRequired]   BIT            NULL,
    [IsProcedureApproved]           BIT            NULL,
    [ProcedureStatus]               INT            NULL,
    [PatientToothId]                BIGINT         NULL,
    [PatientTreatmentPlanId]        BIGINT         NULL,
    CONSTRAINT [XPKPatientProcedure] PRIMARY KEY CLUSTERED ([PatientProcedureId] ASC),
    CONSTRAINT [R_409] FOREIGN KEY ([CategoryFilterId]) REFERENCES [TRE].[CategoryFilter] ([CategoryFilterId]),
    CONSTRAINT [R_590] FOREIGN KEY ([VisitId]) REFERENCES [SCH].[Visit] ([VisitId]),
    CONSTRAINT [R_824] FOREIGN KEY ([MasterProcedureId]) REFERENCES [TRE].[MasterProcedure] ([MasterProcedureId]),
    CONSTRAINT [R_828] FOREIGN KEY ([PatientToothId]) REFERENCES [CLI].[PatientTooth] ([PatientToothId])
);

