CREATE TABLE [FAC].[Coupon] (
    [CouponId]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [CouponTypeId]       BIGINT         NOT NULL,
    [CouponTitle]        VARCHAR (150)  NULL,
    [AdjustmentValue]    VARCHAR (20)   NULL,
    [ActiveDate]         DATETIME       NULL,
    [ExpiryDate]         DATETIME       NULL,
    [CouponAdjustmentId] BIGINT         NULL,
    [MasterProcedureId]  BIGINT         NULL,
    [CouponDescription]  VARCHAR (1024) NULL,
    [CouponCode]         CHAR (5)       NULL,
    [CreatedDateTime]    DATETIME       NOT NULL,
    [ModifiedDateTime]   DATETIME       NOT NULL,
    [CreatedByUser]      VARCHAR (80)   NOT NULL,
    [ModifiedByUser]     VARCHAR (80)   NULL,
    [CreatedByProgram]   VARCHAR (80)   NOT NULL,
    [ModifiedByProgram]  VARCHAR (80)   NULL,
    [RecordStatus]       INT            NOT NULL,
    [PromotionId]        BIGINT         NULL,
    [CouponStatusId]     BIGINT         NULL,
    [IsSendToPortal]     SMALLINT       NULL,
    [IsSuperCoupon]      SMALLINT       NULL,
    CONSTRAINT [XPKCoupon] PRIMARY KEY CLUSTERED ([CouponId] ASC),
    CONSTRAINT [R_314] FOREIGN KEY ([CouponTypeId]) REFERENCES [FAC].[CouponType] ([CouponTypeId]),
    CONSTRAINT [R_319] FOREIGN KEY ([CouponAdjustmentId]) REFERENCES [FAC].[CouponAdjustment] ([CouponAdjustmentId]),
    CONSTRAINT [R_595] FOREIGN KEY ([MasterProcedureId]) REFERENCES [TRE].[MasterProcedure] ([MasterProcedureId]),
    CONSTRAINT [R_611] FOREIGN KEY ([PromotionId]) REFERENCES [FAC].[Promotion] ([PromotionId]),
    CONSTRAINT [R_640] FOREIGN KEY ([CouponStatusId]) REFERENCES [FAC].[CouponStatus] ([CouponStatusId])
);

