CREATE TABLE [INS].[Claim] (
    [ClaimId]              BIGINT       IDENTITY (1, 1) NOT NULL,
    [ClaimNumber]          VARCHAR (20) NULL,
    [NPINumber]            VARCHAR (20) NULL,
    [GroupNumber]          VARCHAR (20) NULL,
    [PlanCode]             VARCHAR (20) NULL,
    [ServiceTypeCode]      VARCHAR (20) NULL,
    [CardIssueDate]        DATETIME     NULL,
    [GeneratedDate]        DATETIME     NULL,
    [ClaimTypeId]          BIGINT       NULL,
    [ProviderInsuranceId]  BIGINT       NULL,
    [VisitId]              BIGINT       NULL,
    [ClaimStatusId]        BIGINT       NULL,
    [CreatedDateTime]      DATETIME     NOT NULL,
    [ModifiedDateTime]     DATETIME     NOT NULL,
    [CreatedByUser]        VARCHAR (80) NOT NULL,
    [ModifiedByUser]       VARCHAR (80) NULL,
    [CreatedByProgram]     VARCHAR (80) NOT NULL,
    [ModifiedByProgram]    VARCHAR (80) NULL,
    [RecordStatus]         INT          NOT NULL,
    [StandardCharges]      MONEY        NULL,
    [TreatmentPlanCharges] MONEY        NULL,
    [BalanceAmount]        MONEY        NULL,
    CONSTRAINT [XPKClaim] PRIMARY KEY CLUSTERED ([ClaimId] ASC),
    CONSTRAINT [R_519] FOREIGN KEY ([ClaimTypeId]) REFERENCES [INS].[ClaimType] ([ClaimTypeId]),
    CONSTRAINT [R_521] FOREIGN KEY ([ProviderInsuranceId]) REFERENCES [INS].[ProviderInsurance] ([ProviderInsuranceId]),
    CONSTRAINT [R_680] FOREIGN KEY ([VisitId]) REFERENCES [SCH].[Visit] ([VisitId]),
    CONSTRAINT [R_711] FOREIGN KEY ([ClaimStatusId]) REFERENCES [INS].[ClaimStatus] ([ClaimStatusId])
);

