CREATE TABLE [INS].[Insurance] (
    [InsuranceId]               BIGINT       IDENTITY (1, 1) NOT NULL,
    [SubscriberId]              BIGINT       NOT NULL,
    [InsuranceFacilityId]       VARCHAR (20) NULL,
    [InsurancePayerId]          BIGINT       NULL,
    [InsurancePolicyTypeId]     BIGINT       NULL,
    [ElectronicPayerIdentityId] BIGINT       NULL,
    [InsuranceStageTypeId]      BIGINT       NULL,
    [CreatedDateTime]           DATETIME     NOT NULL,
    [ModifiedDateTime]          DATETIME     NOT NULL,
    [CreatedByUser]             VARCHAR (80) NOT NULL,
    [ModifiedByUser]            VARCHAR (80) NULL,
    [CreatedByProgram]          VARCHAR (80) NOT NULL,
    [ModifiedByProgram]         VARCHAR (80) NULL,
    [RecordStatus]              INT          NOT NULL,
    [GroupId]                   VARCHAR (20) NULL,
    [EmployerId]                BIGINT       NULL,
    [InsuredId]                 VARCHAR (40) NULL,
    [GroupName]                 VARCHAR (20) NULL,
    [PlanName]                  VARCHAR (20) NULL,
    [EmploymentStatusId]        BIGINT       NULL,
    [EffectiveDate]             DATETIME     NULL,
    [CoPay]                     MONEY        NULL,
    [Deductible]                MONEY        NULL,
    [CoInsurance]               INT          NULL,
    CONSTRAINT [XPKInsurance] PRIMARY KEY CLUSTERED ([InsuranceId] ASC),
    CONSTRAINT [R_360] FOREIGN KEY ([SubscriberId]) REFERENCES [ACC].[Subscriber] ([SubscriberId]),
    CONSTRAINT [R_404] FOREIGN KEY ([InsurancePayerId]) REFERENCES [INS].[InsurancePayer] ([InsurancePayerId]),
    CONSTRAINT [R_702] FOREIGN KEY ([InsurancePolicyTypeId]) REFERENCES [INS].[InsurancePolicyType] ([InsurancePolicyTypeId]),
    CONSTRAINT [R_709] FOREIGN KEY ([ElectronicPayerIdentityId]) REFERENCES [INS].[InsurancePayerIdentity] ([ElectronicPayerIdentityId]),
    CONSTRAINT [R_710] FOREIGN KEY ([InsuranceStageTypeId]) REFERENCES [INS].[InsuranceStageType] ([InsuranceStageTypeId])
);

